### ISSUE TITLE
panic: non-positive interval for NewTicker

### ISSUE THREAD

**Issue by locxiang** [lovoo/goka#255] opened 2020-05-07 06:15 UTC
Kafka version 2.3.1

```
=== RUN   TestExample
message emitted
2020/05/07 13:59:09 Processor [example-group]: starting
2020/05/07 13:59:09 Processor [example-group]: creating consumer 
2020/05/07 13:59:09 Processor [example-group]: creating producer
2020/05/07 13:59:09 Processor: rebalancing: map[]
2020/05/07 13:59:09 Processor: dispatcher started
panic: non-positive interval for NewTicker

goroutine 98 [running]:
time.NewTicker(0x0, 0x0)
	/usr/local/go/src/time/tick.go:23 +0x147
github.com/bsm/sarama-cluster.(*Consumer).cmLoop(0xc0002f4000, 0xc0002ba900)
	/Users/xianghao/go/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/consumer.go:452 +0x5a
github.com/bsm/sarama-cluster.(*loopTomb).Go.func1(0xc0002a4f00, 0xc000310520)
	/Users/xianghao/go/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/util.go:73 +0x7b
created by github.com/bsm/sarama-cluster.(*loopTomb).Go
	/Users/xianghao/go/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/util.go:69 +0x66

Process finished with exit code 1
```

**Comment by frairon** [comment] 2020-05-07 20:35
Thanks for the issue report @locxiang.
Do you have any more details on how to reproduce that? Did you try the new version `v0.9.0-beta3` we're currently working on? This removes sarama-cluster and hopefully has less issues with kafka>0.11 (which the current master version has).

**Comment by foxish** [comment] 2020-05-21 18:21
Just ran into this same issue. Fixed in the new version without sarama-cluster.
```
go get -u github.com/lovoo/goka@v0.9.0-beta3
```

**Comment by R053NR07** [comment] 2020-07-01 11:32
Hey,
as far as I know this problem appears with v0.1.4 and older when the sarama version used is too high. That's not obvious since there is no vendoring in these versions. You can try downgrading sarama go something like v1.20.1. Maybe newer versions will also work but not sure which exactly.

This problem will be solved when the new release is finished.

**Comment by R053NR07** [comment] 2020-07-03 12:57
@foxish is it okay for you to close this issue now or do you need some more help?

**Closed** 2020-07-06 06:35 UTC
