### ISSUE TITLE
Proposal: support static partitioning

### ISSUE THREAD

**Issue by mhaitjema** [lovoo/goka#163] opened 2018-12-11 00:31 UTC
I know the ability to automatically rebalance is a key selling point of goka but if one had to run a goka processor with statically assigned partitions, what would be the easiest way to accomplish that? My first thought would be to generate an assignment notification and provide that groupConsumer but I don't think that will work since the assignment has to actually come from the group coordinator for the Sarama cluster client register the assignment so it can begin receiving  & committing the offsets. The confluence consumer does seem to expose the Assign API but I wasn't sure whether using the confluence consumer is fully supported at this point. I could scrap using the group consumer all together and use the Sarama client to create partition consumers but that would seem to require doing a lot of violence to the frameowork so was wondering what your thoughts were. Thanks in advance!

**Comment by db7** [comment] 2018-12-12 19:09
@mhaitjema I think the decision about the partitions is done inside sarama-cluster's [balancer](https://github.com/bsm/sarama-cluster/blob/b92bef2341de4501b89731753e484c0ec993777b/balancer.go#L161).

Possibly, if you give deterministic clientIDs to your processor instances, you'll get a deterministic partitioning.

The strategy used by the balancer can be further configured using the consumer builder:

 ```
p, err := goka.NewProcessor(
  goka.DefineGroup(...),
  goka.WithClientID("id-1"),
  goka.WithConsumerBuilder(
    kafka.ConsumerBuilderWithConfig(config)))
```

`config` is a Sarama-cluster config object and there you can configure the strategy.

Does this solve your issue?

**Comment by mhaitjema** [comment] 2018-12-12 20:11
Thanks for the reply. Unfortunately in our context we actually need to prevent the possibility of a rebalance from occurring as we want to the same set of static partitions to always be used regardless of whether an instance drops off. Is there anyway to force the existing group consumer to accept a static assignment or would we need to use the confluent consumer (which supports the Assign API)?

**Comment by mhaitjema** [comment] 2018-12-13 19:02
Thanks, @db7 I think I will go the latter route.

**Comment by frairon** [comment] 2020-02-03 08:45
Since the issue is pretty old, I guess it's not such an important issue anymore. However, after upgrading to sarama's ConsumerGroup there's a config option https://godoc.org/github.com/Shopify/sarama#BalanceStrategy that looks like it enables static mapping when applied properly. Will close this for now. Feel free to reopen if it's still important.

**Closed by frairon** 2020-02-03 08:45 UTC
Labels: feature-request
