### ISSUE TITLE
Question: Auto-commit?

### ISSUE THREAD

**Issue by ryanolds-drizly** [lovoo/goka#369] opened 2022-01-10 19:40 UTC
Is auto-commit being disabled on the consumers? I've looked through the code and didn't see anything overriding Sarama's default value, which is to have it enabled.

**Comment by db7** [comment] 2022-01-11 07:44
With the old sarama version it was definitely disabled. If it is not disabled now, then this is a problem.

**Comment by frairon** [comment] 2022-01-12 06:23
Auto-Commit is enabled by default, that's right. Not sure why it would be a problem. Why are you asking?

@db7 I checked the old configs but can't find it being disabled anywhere, could you point me to where you mean?

But maybe there's a misunderstanding here between committing and marking messages? When the processor consumes messages, it marks them after a successful consuming them. Then at specified intervals, the auto-commiter commits those marked offsets to the brokers. If it wasn't, everything would be reconsumed after the next restart. Also if the processor shuts down, it commits all marked offsets one more time. 

Only if the processor does not mark the messages as consumed, they will be reconsumed. The only way to not mark them is failing the processor.

You guys got me a little scared that something was broken, so I wrote two system tests [in this branch](https://github.com/lovoo/goka/blob/commit-test/systemtest/commit_test.go) that show
* a processor with autocommit disabled - started twice and reconsuming all messages
* a processor which crashes after the second message (so it does not mark it as consumed), and reconsumes that message on second run.

Does that clarify things or am I missing the point here?

**Comment by db7** [comment] 2022-01-12 07:09
If I remember correctly the old version used to manually commit consumed messages once all emitted messages (downstream and to table topics) were confirmed. That was triggered in Goka context  ([here](https://github.com/lovoo/goka/blob/1b0a5c2ba27dd3f3822f5b6685d8817f379c8752/context.go#L344) is an arbitrary old commit).
That was the actual motivation... to keep the confirmation of all these events tied together **before** committing upstream.

The commit function was like this, created in `processor.go`:
```go
	ctx.commit = func() {
		// write group table offset to local storage
		if ctx.counters.stores > 0 {
			if offset, err := ctx.storage.GetOffset(0); err != nil {
				ctx.failer(fmt.Errorf("error getting storage offset for %s/%d: %v",
					g.graph.GroupTable().Topic(), msg.Partition, err))
				return
			} else if err = ctx.storage.SetOffset(offset + int64(ctx.counters.stores)); err != nil {
				ctx.failer(fmt.Errorf("error writing storage offset for %s/%d: %v",
					g.graph.GroupTable().Topic(), msg.Partition, err))
				return
			}
		}

		// mark upstream offset
		if err := g.consumer.Commit(msg.Topic, msg.Partition, msg.Offset); err != nil {
			g.fail(fmt.Errorf("error committing offsets of %s/%d: %v",
				g.graph.GroupTable().Topic(), msg.Partition, err))
		}
	}
```


The wrapper of Sarama and Confluent drivers had this interface (`kafka.Consumer`):

```go
type Consumer interface {
	Events() <-chan Event

	// group consume assumes co-partioned topics
	// define input topics to consume
	Subscribe(topics map[string]int64) error
	// marks the consumer ready to start consuming the messages
	AddGroupPartition(partition int32)
	Commit(topic string, partition int32, offset int64) error

	// consume individual topic/partitions
	AddPartition(topic string, partition int32, initialOffset int64) error
	RemovePartition(topic string, partition int32) error

	// Close stops closes the events channel
	Close() error
}
```

And `Commit(...)` for Sarama was implemented like this:

```go
func (c *groupConsumer) Commit(topic string, partition int32, offset int64) error {
	c.consumer.MarkPartitionOffset(topic, partition, offset, "")
	return nil
}```

I cannot remember if Sarama's `Consumer.Offsets.AutoCommit.Enable` ​field was set within Goka or if we had that only in Lovoo's internal builder, but it should be disabled otherwise the whole commit logic is useless, AFAICT.

Support for Confluent driver was experimental, there we used auto-commit.

**Comment by db7** [comment] 2022-01-12 07:12
@frairon After rereading your message, I think my memory may be just too blurry. It sounds right what you said: the auto-commit of Sarama only commits those that are marked, and we mark them. I think that in Confluent driver the messages were really auto-committed (but again, my memory may fool me). Sorry for the false alarm.

**Comment by frairon** [comment] 2022-01-12 08:41
No worries, always good to double-check and the systemtest doesn't hurt. Also, the wording is a bit misleading, I got unsure about the same thing too when we migrated to the new version.

**Comment by ryanolds-drizly** [comment] 2022-01-12 16:31
Thank you looking into this. This aligns with at-least-once semantics. I'm looking into if it's possible to configure Goka to operate closer to exactly-once semantics, and I think I'm hear that it is with some configuration changes.

**Comment by frairon** [comment] 2022-01-13 12:40
No problem, yes goka provides at-least-once semantics. Having exactly-once-semantics however won't be possible right now, because sarama does not provide that feature. 
One way to get closer to that, is building idempotent operations. You could e.g. store the latest offset used to update a state and ignore older offsets.

**Comment by frairon** [comment] 2022-03-24 09:03
closing this, as it seems to be clarified now.

**Closed by frairon** 2022-03-24 09:03 UTC
