### ISSUE TITLE
Go get error

### ISSUE THREAD

**Issue by dawei101** [lovoo/goka#213] opened 2019-12-10 08:28 UTC
```
 go get github.com/lovoo/goka
# github.com/bsm/sarama-cluster
../../bsm/sarama-cluster/consumer.go:452:59: c.client.config.Config.Consumer.Offsets.CommitInterval undefined (type struct { AutoCommit struct { Enable bool; Interval time.Duration }; Initial int64; Retention time.Duration; Retry struct { Max int } } has no field or method CommitInterval)
```

**Comment by suohailong** [comment] 2020-01-20 04:10
I have the same issue

**Comment by frairon** [comment] 2020-01-21 10:15
So the issue is, that sarama-cluster (which is deprecated) became incompatible with sarama at some point. The only workaround is to downgrade your sarama version, e.g. `v1.22.1`. That should resolve the compiler issues.

**Comment by frairon** [comment] 2020-01-27 07:55
I'll close this, it's a duplicate of #211

**Closed by frairon** 2020-01-27 07:55 UTC
