### ISSUE TITLE
Race condition error when running tests

### ISSUE THREAD

**Issue by cioboteacristian** [lovoo/goka#202] opened 2019-10-04 09:23 UTC
I tried to run a test that chains two processors, following your example from https://github.com/lovoo/goka/blob/master/examples/4-tests/example_test.go#Test_Chain . It works fine until I add the -race flag to the test runner. 

After debugging for half a day and trying to improve my code, I actually tried to run the tests provider by you (in the aforementioned file), and it turns out that there is the same issue (and a lot more other data race errors).

I believe that the issue is somewhere in the tester package itself.

```
WARNING: DATA RACE
Read at 0x00c000498008 by goroutine 87:
  github.com/lovoo/goka/tester.(*queue).waitConsumersInit()
      /Users/cristianciobotea/go/pkg/mod/github.com/lovoo/goka@v0.1.3/tester/signal.go:59 +0x26b

Previous write at 0x00c000498008 by goroutine 98:
  github.com/lovoo/goka/tester.(*Signal).SetState()
      /Users/cristianciobotea/go/pkg/mod/github.com/lovoo/goka@v0.1.3/tester/signal.go:43 +0x117
```

**Comment by db7** [comment] 2019-10-12 11:49
@TheL1ne Is this related to your latest PR?

**Comment by cioboteacristian** [comment] 2019-10-18 08:10
In my own code, I use the tagged release. But, when I try to run test -race on examples/4-tests/example_test.go, I use the latest code. Either way, same problem. Does it actually work for you?

**Comment by TheL1ne** [comment] 2019-10-18 08:24
I can reproduce the problem with the example but it works fine without the race flag. I can only guess what happens here without deeper investigation. But my guess would be that the detection algorithms miss something because we produce and consume asynchronously.

Out of curiosity: why did you add the `-race` flag?

**Comment by cioboteacristian** [comment] 2019-10-18 11:59
We always use -race, because I believe it is good practice (btw, I am new to Go). It is also company policy :)

**Comment by TheL1ne** [comment] 2019-10-23 10:20
@db7 since it also occurs when using the tagged release: no it is not related to my PR.

**Comment by frairon** [comment] 2020-03-22 12:37
@cioboteacristian can you check if you're still having the issue in branch `consumer-group`? This will be the next version as soon as it's stable enough. If it's fixed feel free to close the issue.
Thanks

**Comment by frairon** [comment] 2021-12-19 06:50
let's close this for being inactive for too long.

**Closed by frairon** 2021-12-19 06:50 UTC
