### ISSUE TITLE
Recovery from Broker failure

### ISSUE THREAD

**Issue by juliusbachnick** [lovoo/goka#194] opened 2019-06-24 13:01 UTC
Hey everyone,

I just tried the `2-clicks` example with multiple brokers to see how failure recovery works. For the example, I configured 3 brokers and the topics `user-click` and `mini-group-table` (each with 1 partition and 2 replicas). I modified the example slightly to connect to them:
```diff
--- a/examples/2-clicks/main.go
+++ b/examples/2-clicks/main.go
@@ -13,7 +13,7 @@ import (
 )

 var (
-       brokers             = []string{"127.0.0.1:9092"}
+       brokers             = []string{"127.0.0.1:9092", "127.0.0.1:9093", "127.0.01:9094"}
        topic   goka.Stream = "user-click"
        group   goka.Group  = "mini-group"
 )
```

After the example programm was up, I killed one of the brokers, assuming that the programm would recover and continue. Unfortunately this was not the case (I truncated the logs):

```
2019/06/24 14:57:40 Table mini-group-table has 1 partitions
2019/06/24 14:57:40 Processor: starting
2019/06/24 14:57:40 Processor: creating consumer [mini-group]
2019/06/24 14:57:40 Processor: creating producer
View opened at http://localhost:9095/
2019/06/24 14:57:40 view: starting
2019/06/24 14:57:40 view: partition 0 started
2019/06/24 14:57:41 Processor: rebalancing: map[]
2019/06/24 14:57:41 Processor: dispatcher started
2019/06/24 14:57:41 Processor: dispatcher stopped
2019/06/24 14:57:41 Processor: rebalancing: map[0:-1]
2019/06/24 14:57:41 Processor: dispatcher started
[proc] key: user-7 clicks: 10, msg: 2019-06-24 14:57:41.725721321 +0200 CEST m=+1.046297686
[proc] key: user-8 clicks: 10, msg: 2019-06-24 14:57:41.827466193 +0200 CEST m=+1.148042550
[proc] key: user-9 clicks: 10, msg: 2019-06-24 14:57:41.93291159 +0200 CEST m=+1.253488148
[proc] key: user-1 clicks: 10, msg: 2019-06-24 14:57:42.14345402 +0200 CEST m=+1.464030527
[proc] key: user-2 clicks: 10, msg: 2019-06-24 14:57:42.245094454 +0200 CEST m=+1.565670805
[proc] key: user-3 clicks: 10, msg: 2019-06-24 14:57:42.350240296 +0200 CEST m=+1.670816891
[proc] key: user-4 clicks: 10, msg: 2019-06-24 14:57:42.455037588 +0200 CEST m=+1.775614012
[proc] key: user-5 clicks: 10, msg: 2019-06-24 14:57:42.559739661 +0200 CEST m=+1.880316086
[proc] key: user-6 clicks: 10, msg: 2019-06-24 14:57:42.665038129 +0200 CEST m=+1.985614632
[...]
[proc] key: user-7 clicks: 18, msg: 2019-06-24 14:57:50.102345708 +0200 CEST m=+9.422922163
[proc] key: user-8 clicks: 18, msg: 2019-06-24 14:57:50.207830233 +0200 CEST m=+9.528406821
[proc] key: user-9 clicks: 18, msg: 2019-06-24 14:57:50.312226741 +0200 CEST m=+9.632803226
[proc] key: user-0 clicks: 19, msg: 2019-06-24 14:57:50.41652433 +0200 CEST m=+9.737100821
[proc] key: user-1 clicks: 18, msg: 2019-06-24 14:57:50.521306348 +0200 CEST m=+9.841882887
[proc] key: user-2 clicks: 18, msg: 2019-06-24 14:57:50.626013151 +0200 CEST m=+9.946589677
[proc] key: user-3 clicks: 18, msg: 2019-06-24 14:57:50.728759146 +0200 CEST m=+10.049335602
[proc] key: user-4 clicks: 18, msg: 2019-06-24 14:57:50.833781073 +0200 CEST m=+10.154357650
[proc] key: user-5 clicks: 18, msg: 2019-06-24 14:57:50.939306572 +0200 CEST m=+10.259882996
[proc] key: user-6 clicks: 18, msg: 2019-06-24 14:57:51.044033031 +0200 CEST m=+10.364609578
[proc] key: user-7 clicks: 19, msg: 2019-06-24 14:57:51.148181014 +0200 CEST m=+10.468757475
[proc] key: user-8 clicks: 19, msg: 2019-06-24 14:57:51.253027918 +0200 CEST m=+10.573604391
[proc] key: user-9 clicks: 19, msg: 2019-06-24 14:57:51.358392359 +0200 CEST m=+10.678968814
[proc] key: user-0 clicks: 20, msg: 2019-06-24 14:57:51.463633506 +0200 CEST m=+10.784210025
[proc] key: user-1 clicks: 19, msg: 2019-06-24 14:57:51.568785163 +0200 CEST m=+10.889361713
[proc] key: user-2 clicks: 19, msg: 2019-06-24 14:57:51.673096815 +0200 CEST m=+10.993673255
[proc] key: user-3 clicks: 19, msg: 2019-06-24 14:57:51.777933424 +0200 CEST m=+11.098509887
[proc] key: user-4 clicks: 19, msg: 2019-06-24 14:57:51.882211586 +0200 CEST m=+11.202788001
2019/06/24 14:57:52 Processor: dispatcher stopped
2019/06/24 14:57:52 partition mini-group-table/0: exit
2019/06/24 14:57:52 Removing partition 0
2019/06/24 14:57:52 Processor: removing partitions
2019/06/24 14:57:52 Processor: closing producer
2019/06/24 14:57:52 Processor: closing consumer [mini-group]
2019/06/24 14:57:52 Processor: stopped
```

I looked up the documentation but was unable to find how to configure goka in way, that a processor is not stopped if a kafka broker goes down.

Could you please point me in the direction how this can be achieved with goka?

**Comment by frairon** [comment] 2019-06-24 19:40
Hi juliusbachnick,

the processor will always shutdown when there's an error communicating with Kafka. If you have multiple brokers and restart one of them, some partitions will be without leader, which makes Kafka do a leader-reelection. The processor fails, because it tries to send data to the offline broker (or some broker that is not the leader of the partition). 
Usually we expect the server processes to run in some kind of managed environment (like kubernetes), which restarts the processes once they have failed. I'd suggest to do that, if you have the possibility, because a clean start-up is always better than trying to recover from some error.
If the process must continue to live, you can could run the `proc.Run(ctx)` method in some kind of loop. On every error `proc.Run(ctx)` will return with an error and the loop can restart it. In this case however, also think about backoff times and/or circuit breakers to avoid too much load on the brokers if there's a real issue.
In the documentation, recovery means that Lookup/Join/Persist-tables that the processor might use, will be fully recovered to avoid data loss or inconsistencies after a failure.

Let me know if that helps with your issue

**Comment by juliusbachnick** [comment] 2019-06-25 11:35
Hey  frairon,

That's what I did now: I wrapped the `proc.Run(ctx)` in a loop which would rerun the process if it failed. Also, I created the corresponding view using the option `goka.WithViewRestartable()` and terminate the view manually if the loop finishes. Seems to work so far :+1:

**Comment by frairon** [comment] 2019-06-25 12:58
Awesome, that's the way to go!

**Comment by frairon** [comment] 2019-07-01 06:08
@juliusbachnick seems like the issue is solved for you, so I'll close it. If you still have problems, feel free to reopen or create a new one.

**Closed by frairon** 2019-07-01 06:08 UTC
Labels: question
