### ISSUE TITLE
LevelDB writes failing when writing the journal

### ISSUE THREAD

**Issue by rohit-msd** [lovoo/goka#272] opened 2020-09-22 20:57 UTC
I'm using a goka View to serve data in a HTTP server. Lately, the view has been failing with the following error which seems like leveldb is failing to write to the journal file when setting a key in the db with the following error.
```
error setting to leveldb (key eb351d11-db61-49e4-9f45-24a579b58f40): write /tables/table.9/000215.log: cannot allocate memory  
```

It happens only in one of the replica of the process (there are 3 replicas). 

NOTE:
* The size of the keys is 32 bytes, values is 163 bytes.
* The LOG file doesn't show any bad blocks etc.
* Using default settings for leveldb, version v1.0.0 
* These are the contents of the directory when the issue happened.
```
# ls -alh ./
total 29M    
drwxr-xr-x    2 root     root        4.0K Sep 22 16:58 .
drwxr-xr-x    3 root     root        4.0K Sep 22 16:58 ..
-rw-r--r--    1 root     root        3.6M Sep 22 16:58 000215.log
-rw-r--r--    1 root     root        2.0M Sep 22 16:58 000218.ldb
-rw-r--r--    1 root     root        2.0M Sep 22 16:58 000219.ldb
-rw-r--r--    1 root     root        2.0M Sep 22 16:58 000220.ldb
-rw-r--r--    1 root     root        2.0M Sep 22 16:58 000221.ldb
-rw-r--r--    1 root     root        2.0M Sep 22 16:58 000222.ldb
-rw-r--r--    1 root     root        2.0M Sep 22 16:58 000223.ldb
-rw-r--r--    1 root     root        2.0M Sep 22 16:58 000224.ldb
-rw-r--r--    1 root     root        2.0M Sep 22 16:58 000225.ldb
-rw-r--r--    1 root     root        2.0M Sep 22 16:58 000226.ldb
-rw-r--r--    1 root     root        2.0M Sep 22 16:58 000227.ldb
-rw-r--r--    1 root     root        2.0M Sep 22 16:58 000228.ldb
-rw-r--r--    1 root     root        2.0M Sep 22 16:58 000229.ldb
-rw-r--r--    1 root     root      584.6K Sep 22 16:58 000230.ldb
-rw-r--r--    1 root     root          16 Sep 22 16:58 CURRENT
-rw-r--r--    1 root     root          16 Sep 22 16:58 CURRENT.bak
-rw-r--r--    1 root     root           0 Sep 22 16:58 LOCK
-rw-r--r--    1 root     root       41.1K Sep 22 16:58 LOG
-rw-r--r--    1 root     root        2.9K Sep 22 16:58 MANIFEST-000216
```

I'm unable to reproduce the issue nor trace the root cause of the issue.

This is how I am creating the view:
```
func (r *ResultStore) updateCallback(s storage.Storage, partition int32, key string, value []byte) error {
	err := goka.DefaultUpdate(s, partition, key, value)
        // some custom code that does a few go channel pushes
	return err
}

func NewResultStore(opts *ResultStoreOptions) (*ResultStore, error) {
	r := &ResultStore{}
	view, err := goka.NewView(brokers,
		goka.GroupTable(groups.ProcessorGroup), goka.Codec(new(groups.JsonCodec)),
		goka.WithViewStorageBuilder(storage.DefaultBuilder("/tables")),
		goka.WithViewRestartable(),
		goka.WithViewCallback(r.updateCallback))
	if err != nil {
		return nil, err
	}
	r.view = view
	ctx, cancel := context.WithCancel(context.Background())
	r.wg.Add(1)
	go func() {
		for {
			err := view.Run(ctx)
			if err != nil {
				log.Println("Error running result store view, restarting, err:", err)
				time.Sleep(100 * time.Millisecond)
			} else {
				break
			}
		}
		err := view.Terminate()
		if err != nil {
			log.Println("Error terminating result store view, err:", err)
		}
		r.wg.Done()
	}()
	r.cancel = cancel
	return r, nil
}
```

A restart of the replica fixes the problem but the view fails to recover until the process restart until it appears again.

cc @syndtr (tagging you since goka uses goleveldb, please let me know if you want an issue to be opened in the goleveldb repo instead, thanks!)

**Comment by frairon** [comment] 2020-10-10 11:30
Hi @rohit-msd, are you sure the issue is disk related? The message "cannot allocate memory" actually sounds like the machine is out of memory and failing when writing the log is just coincidence, could happen anywhere else too. 
What I'd suggestion though, is to migrate to the new goka version (>1.0.0), as it has many improvements over the previous version. For example, the reconnect/retry logic of a view is builtin, so you don't need the manual retry if `view.Run(ctx)` fails. See the [Migration](https://github.com/lovoo/goka/blob/master/MIGRATION.md) guide.

Let us know if you're still having issues or close the issue if it's resolved for you.
Cheers!

**Comment by frairon** [comment] 2021-02-10 19:10
closed the issue because of lack of activity. feel free to reopen/create new issue if you're still facing any problems.

**Closed** 2021-02-10 19:09 UTC
